name: fireproof_closet
description: Cache your Firebase Storage images to the Fireproof Closet for blazingly fast access.
version: 0.90.1
homepage:

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^11.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  hive_generator: ^2.0.0

# The following section is specific to Flutter packages.
flutter: